/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.cucumber.core.runtime;

import java.awt.event.MouseEvent;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author gilga
 */
public class UserInputFeatureSupplierForm extends javax.swing.JFrame {

    private UserInputFeatureSupplier supplier = null;

    /**
     * Creates new form UserInputFeatureSupplierForm
     */
    public UserInputFeatureSupplierForm(UserInputFeatureSupplier s) {
        this.supplier = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setGherkinFolderMenu = new javax.swing.JPopupMenu();
        setGherkinFolderButtonMenuItem = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        gherkinTextAreaScrollPane = new javax.swing.JScrollPane();
        gherkinTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gherkinFolderTree = new javax.swing.JTree();
        executeButton = new javax.swing.JButton();
        loadFileButton = new javax.swing.JButton();

        setGherkinFolderButtonMenuItem.setText("Set Gherkin Folder");
        setGherkinFolderButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGherkinFolderButtonMenuItemActionPerformed(evt);
            }
        });
        setGherkinFolderMenu.add(setGherkinFolderButtonMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setVerifyInputWhenFocusTarget(false);

        gherkinTextArea.setColumns(20);
        gherkinTextArea.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        gherkinTextArea.setRows(5);
        gherkinTextArea.setText("Feature: Basic Arithmetic\n  Scenario: Addition     \n    Given a calculator I just turned on     \n    When I add 4 and 5     \n    Then the result is 9"); // NOI18N
        gherkinTextArea.setDragEnabled(true);
        gherkinTextAreaScrollPane.setViewportView(gherkinTextArea);

        jSplitPane1.setLeftComponent(gherkinTextAreaScrollPane);

        gherkinFolderTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gherkinFolderTreeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(gherkinFolderTree);

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        loadFileButton.setText("Load File");
        loadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeButton)
                    .addComponent(loadFileButton)))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        this.supplier.actionPerformed(evt);
    }//GEN-LAST:event_executeButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.supplier.windowClosing(evt);
    }//GEN-LAST:event_formWindowClosing

    private void loadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Feature File", "feature"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String fileContents = null;
            try {
                fileContents = new String(Files.readAllBytes(Paths.get(fileChooser.getSelectedFile().getPath())));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            this.gherkinTextArea.setText(fileContents);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setGherkinFolderButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGherkinFolderButtonMenuItemActionPerformed
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setAcceptAllFileFilterUsed(false);
        int result = folderChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Set the tree view to the selected directory
        }
    }//GEN-LAST:event_setGherkinFolderButtonMenuItemActionPerformed

    private void gherkinFolderTreeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gherkinFolderTreeMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3) {
            this.setGherkinFolderMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_gherkinFolderTreeMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeButton;
    private javax.swing.JTree gherkinFolderTree;
    public javax.swing.JTextArea gherkinTextArea;
    private javax.swing.JScrollPane gherkinTextAreaScrollPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loadFileButton;
    private javax.swing.JMenuItem setGherkinFolderButtonMenuItem;
    private javax.swing.JPopupMenu setGherkinFolderMenu;
    // End of variables declaration//GEN-END:variables
}
