/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.cucumber.core.runtime;

/**
 *
 * @author gilga
 */
public class UserInputFeatureSupplierForm extends javax.swing.JFrame {

    private UserInputFeatureSupplier supplier = null;

    /**
     * Creates new form UserInputFeatureSupplierForm
     */
    public UserInputFeatureSupplierForm(UserInputFeatureSupplier s) {
        this.supplier = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gherkinTextAreaScrollPane = new javax.swing.JScrollPane();
        gherkinTextArea = new javax.swing.JTextArea();
        executeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        gherkinTextArea.setColumns(20);
        gherkinTextArea.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        gherkinTextArea.setRows(5);
        gherkinTextArea.setText("Feature: Basic Arithmetic\n  Scenario: Addition     \n    Given a calculator I just turned on     \n    When I add 4 and 5     \n    Then the result is 9"); // NOI18N
        gherkinTextArea.setDragEnabled(true);
        gherkinTextAreaScrollPane.setViewportView(gherkinTextArea);

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gherkinTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(executeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(executeButton))
                    .addComponent(gherkinTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        this.supplier.actionPerformed(evt);
    }//GEN-LAST:event_executeButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.supplier.windowClosing(evt);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeButton;
    public javax.swing.JTextArea gherkinTextArea;
    private javax.swing.JScrollPane gherkinTextAreaScrollPane;
    // End of variables declaration//GEN-END:variables
}
