/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.cucumber.core.runtime;

import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Objects;
import javax.swing.*;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author gilga
 */
public class UserInputFeatureSupplierForm extends javax.swing.JFrame {

    private UserInputFeatureSupplier supplier = null;
    private String folderRoot;
    private String scenarioTagText;

    /**
     * Creates new form UserInputFeatureSupplierForm
     */
    public UserInputFeatureSupplierForm(UserInputFeatureSupplier s) {
        this.supplier = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scenarioTagDialog = new javax.swing.JDialog();
        scenarioTagLabel = new javax.swing.JLabel();
        scenarioTagTextField = new javax.swing.JTextField();
        scenarioTagOKButton = new javax.swing.JButton();
        scenarioTagCancelButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        gherkinTextAreaScrollPane = new javax.swing.JScrollPane();
        gherkinTextArea = new javax.swing.JTextArea();
        fileTreePanel = new javax.swing.JPanel();
        fileTreeScrollPane = new javax.swing.JScrollPane();
        gherkinFileFolderTree = new javax.swing.JTree();
        executeButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        setScenarioTagMenuItem = new javax.swing.JMenuItem();
        setGherkinFolderButtonMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        scenarioTagDialog.setResizable(false);

        scenarioTagLabel.setText("Scenario Tag");

        scenarioTagOKButton.setText("OK");
        scenarioTagOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scenarioTagOKButtonActionPerformed(evt);
            }
        });

        scenarioTagCancelButton.setText("Cancel");
        scenarioTagCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scenarioTagCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout scenarioTagDialogLayout = new javax.swing.GroupLayout(scenarioTagDialog.getContentPane());
        scenarioTagDialog.getContentPane().setLayout(scenarioTagDialogLayout);
        scenarioTagDialogLayout.setHorizontalGroup(
            scenarioTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scenarioTagDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scenarioTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scenarioTagDialogLayout.createSequentialGroup()
                        .addComponent(scenarioTagLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scenarioTagTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scenarioTagDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scenarioTagOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scenarioTagCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        scenarioTagDialogLayout.setVerticalGroup(
            scenarioTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scenarioTagDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scenarioTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scenarioTagLabel)
                    .addComponent(scenarioTagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scenarioTagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scenarioTagOKButton)
                    .addComponent(scenarioTagCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setVerifyInputWhenFocusTarget(false);

        gherkinTextArea.setColumns(20);
        gherkinTextArea.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        gherkinTextArea.setRows(5);
        gherkinTextArea.setText("Feature: Basic Arithmetic\n  Scenario: Addition     \n    Given a calculator I just turned on     \n    When I add 4 and 5     \n    Then the result is 9"); // NOI18N
        gherkinTextArea.setDragEnabled(true);
        gherkinTextAreaScrollPane.setViewportView(gherkinTextArea);

        jSplitPane1.setLeftComponent(gherkinTextAreaScrollPane);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Set Gherkin root folder in File->Settings");
        gherkinFileFolderTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        gherkinFileFolderTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                gherkinFileFolderTreeValueChanged(evt);
            }
        });
        fileTreeScrollPane.setViewportView(gherkinFileFolderTree);

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileTreePanelLayout = new javax.swing.GroupLayout(fileTreePanel);
        fileTreePanel.setLayout(fileTreePanelLayout);
        fileTreePanelLayout.setHorizontalGroup(
            fileTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileTreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGroup(fileTreePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fileTreePanelLayout.setVerticalGroup(
            fileTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileTreePanelLayout.createSequentialGroup()
                .addComponent(fileTreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executeButton))
        );

        jSplitPane1.setRightComponent(fileTreePanel);

        fileMenu.setText("File");
        fileMenu.setPreferredSize(new java.awt.Dimension(36, 22));

        loadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        loadMenuItem.setText("Load");
        loadMenuItem.setPreferredSize(new java.awt.Dimension(200, 22));
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadMenuItem);

        settingsMenu.setText("Settings");

        setScenarioTagMenuItem.setText("Set Scenario Tag");
        setScenarioTagMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setScenarioTagMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(setScenarioTagMenuItem);

        setGherkinFolderButtonMenuItem.setText("Set Gherkin Folder");
        setGherkinFolderButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGherkinFolderButtonMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(setGherkinFolderButtonMenuItem);

        fileMenu.add(settingsMenu);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        this.supplier.actionPerformed(evt);
    }//GEN-LAST:event_executeButtonActionPerformed

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.supplier.windowClosing(evt);
    }//GEN-LAST:event_formWindowClosing

    private static void buildFileTree(File dir, DefaultMutableTreeNode node) {
        for (File file : Objects.requireNonNull(dir.listFiles())) {
            DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(file.getName());
            node.add(childNode);
            if (file.isDirectory()) {
                buildFileTree(file, childNode);
            }
        }
    }

    private void setGherkinFolderButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGherkinFolderButtonMenuItemActionPerformed
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setAcceptAllFileFilterUsed(false);
        int result = folderChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Set the tree view to the selected directory
            this.folderRoot = folderChooser.getSelectedFile().getPath();
            DefaultMutableTreeNode root = new DefaultMutableTreeNode();
            buildFileTree(folderChooser.getSelectedFile(), root);
            this.gherkinFileFolderTree.setModel(new DefaultTreeModel(root));
        }
    }//GEN-LAST:event_setGherkinFolderButtonMenuItemActionPerformed

    private void gherkinFileFolderTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_gherkinFileFolderTreeValueChanged
        // Convert the event treepath to a file path
        String file = getPathFromTreeNode(evt);
        if (file.endsWith(".feature")) {
            try {
                gherkinTextArea.setText(new String(Files.readAllBytes(Paths.get(this.folderRoot + file))));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        } else {
            gherkinTextArea.setText("");
        }
    }//GEN-LAST:event_gherkinFileFolderTreeValueChanged

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Feature File", "feature"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String fileContents = null;
            try {
                fileContents = new String(Files.readAllBytes(Paths.get(fileChooser.getSelectedFile().getPath())));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            this.gherkinTextArea.setText(fileContents);
            this.gherkinFileFolderTree.setSelectionPath(null);
        }
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void setScenarioTagMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setScenarioTagMenuItemActionPerformed
        this.scenarioTagDialog.setVisible(true);
    }//GEN-LAST:event_setScenarioTagMenuItemActionPerformed

    private void scenarioTagOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scenarioTagOKButtonActionPerformed
        this.scenarioTagText = this.scenarioTagTextField.getText();
    }//GEN-LAST:event_scenarioTagOKButtonActionPerformed

    private void scenarioTagCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scenarioTagCancelButtonActionPerformed
        this.scenarioTagDialog.setVisible(false);
    }//GEN-LAST:event_scenarioTagCancelButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // Close the application
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private static String getPathFromTreeNode(TreeSelectionEvent evt) {
        return evt.getPath().toString().replace(
            "[", "").replace(
            "]", "").replace(
            ", ", File.separator).replace(
            " ", "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel fileTreePanel;
    private javax.swing.JScrollPane fileTreeScrollPane;
    private javax.swing.JTree gherkinFileFolderTree;
    public javax.swing.JTextArea gherkinTextArea;
    private javax.swing.JScrollPane gherkinTextAreaScrollPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton scenarioTagCancelButton;
    private javax.swing.JDialog scenarioTagDialog;
    private javax.swing.JLabel scenarioTagLabel;
    private javax.swing.JButton scenarioTagOKButton;
    private javax.swing.JTextField scenarioTagTextField;
    private javax.swing.JMenuItem setGherkinFolderButtonMenuItem;
    private javax.swing.JMenuItem setScenarioTagMenuItem;
    private javax.swing.JMenu settingsMenu;
    // End of variables declaration//GEN-END:variables
}
